<?php

return [
    'Analgesics and Anti-inflammatory' => [
        'Acetylsalicylic acid',
        'Celecoxib',
        'Codeine',
        'Diclofenac',
        'Ibuprofen',
        'Meloxicam',
        'Morphine',
        'Naproxen',
        'Paracetamol',
        'Tramadol'
    ],
    'Antibiotics' => [
        'Amikacin',
        'Amoxicillin',
        'Amoxicillin with clavulanic acid',
        'Ampicillin',
        'Azithromycin',
        'Benzathine benzylpenicillin',
        'Benzylpenicillin',
        'Cefalexin',
        'Cefixime',
        'Cefotaxime',
        'Ceftriaxone',
        'Chloramphenicol',
        'Ciprofloxacin',
        'Clarithromycin',
        'Clindamycin',
        'Cloxacillin',
        'Co-trimoxazole',
        'Cefazolin',
        'Cefepime',
        'Ceftazidime',
        'Doxycycline',
        'Erythromycin',
        'Cefuroxime',
        'Gentamicin',
        'Imipenem with cilastatin',
        'Linezolid',
        'Meropenem',
        'Metronidazole',
        'Nitrofurantoin',
        'Oxacillin',
        'Penicillin V',
        'Piperacillin with tazobactam',
        'Rifabutin',
        'Streptomycin',
        'Tetracycline',
        'Tinidazole',
        'Vancomycin'
    ],
    'Antimalarials and Antiparasitics' => [
        'Albendazole',
        'Artemether',
        'Artemether-lumefantrine',
        'Artesunate',
        'Chloroquine',
        'Ivermectin',
        'Mebendazole',
        'Niclosamide',
        'Permethrin',
        'Primaquine',
        'Quinine'
    ],
    'Antifungals and Antivirals' => [
        'Aciclovir',
        'Clotrimazole',
        'Fluconazole',
        'Ganciclovir',
        'Lamivudine',
        'Miconazole',
        'Nevirapine',
        'Nystatin',
        'Oseltamivir',
        'Tenofovir disoproxil fumarate',
        'Valaciclovir',
        'Valganciclovir',
        'Zidovudine'
    ],
    'Cardiovascular' => [
        'Amiodarone',
        'Amiloride',
        'Amlodipine',
        'Bisoprolol',
        'Atenolol',
        'Atorvastatin',
        'Candesartan',
        'Clopidogrel',
        'Digoxin',
        'Diltiazem',
        'Enalapril',
        'Enoxaparin',
        'Frusemide',
        'Heparin',
        'Hydralazine',
        'Hydrochlorothiazide',
        'Isosorbide dinitrate',
        'Labetalol',
        'Lisinopril',
        'Losartan',
        'Methyldopa',
        'Metoprolol',
        'Nifedipine',
        'Nitroglycerin',
        'Propranolol',
        'Spironolactone',
        'Tranexamic acid',
        'Verapamil',
        'Warfarin'
    ],
    'Diabetes and Endocrine' => [
        'Dexamethasone oral',
        'Glibenclamide',
        'Gliclazide',
        'Glucagon',
        'Insulin isophane',
        'Insulin soluble',
        'Levothyroxine',
        'Metformin'
    ],
    'Respiratory and Allergy' => [
        'Beclometasone',
        'Budesonide',
        'Cetirizine',
        'Chlorphenamine',
        'Diphenhydramine',
        'Hydrocortisone injection',
        'Ipratropium bromide',
        'Salbutamol'
    ],
    'Emergency and Critical Care' => [
        'Activated charcoal',
        'Atropine',
        'Calcium gluconate',
        'Diazepam',
        'Dobutamine',
        'Dopamine',
        'Epinephrine',
        'Glucose',
        'Ketamine',
        'Lidocaine',
        'Magnesium sulfate',
        'Midazolam',
        'Naloxone',
        'Norepinephrine',
        'Oxygen',
        'Ringer lactate',
        'Sodium bicarbonate',
        'Sodium chloride'
    ],
    'Gastrointestinal and Nutrition' => [
        'Bisacodyl',
        'Folic acid',
        'Ferrous sulfate',
        'Hyoscine butylbromide',
        'Lactulose',
        'Loperamide',
        'Metoclopramide',
        'Omeprazole',
        'Ondansetron',
        'Oral rehydration salts',
        'Pyridoxine',
        'Zinc sulfate'
    ],
    'Neurology and Mental Health' => [
        'Amitriptyline',
        'Carbamazepine',
        'Citalopram',
        'Fluoxetine',
        'Haloperidol',
        'Levodopa with carbidopa',
        'Lorazepam',
        'Olanzapine',
        'Phenobarbital',
        'Phenytoin',
        'Risperidone',
        'Sertraline',
        'Valproic acid'
    ],
    'Steroids and Immunology' => [
        'Azathioprine',
        'Betamethasone',
        'Cyclophosphamide',
        'Cyclosporine',
        'Dexamethasone',
        'Hydrocortisone',
        'Methotrexate',
        'Prednisolone',
        'Prednisone',
        'Tamoxifen'
    ],
    'Dermatology and Topicals' => [
        'Benzyl benzoate',
        'Chlorhexidine',
        'Clobetasol',
        'Mupirocin',
        'Silver sulfadiazine',
        'Sulfadiazine'
    ],
    'Obstetrics and Gynecology' => [
        'Clomifene',
        'Ethinylestradiol with levonorgestrel',
        'Levonorgestrel',
        'Misoprostol',
        'Oxytocin'
    ],
    'Tuberculosis and Public Health' => [
        'Bacille Calmette-Guerin vaccine',
        'Ethambutol',
        'Isoniazid',
        'Pyrazinamide',
        'Rabies vaccine',
        'Rifampicin',
        'Bedaquiline'
    ],
    'General' => [
        'Allopurinol',
        'Calcium carbonate',
        'Multivitamin'
    ]
];
